### PR TITLE
[backport from upstream] win, fs: fix non-symlink reparse points

### PR DESCRIPTION
**Pull request by ararslan**
See commit message for full description of change

### CODE REVIEW

**Comment by ihnorton** [comment]
On my phone so might be misreading, but I thought there were a few lines
changed in fs__stat_impl as well.

**Comment by ararslan** [comment]
Nope. At least not in the PR I cherry-picked here.

**Comment by ihnorton** [comment]
The backport itself looks LGTM. I'm not set up to build for Windows right now so I haven't tested. Maybe we can get this in a nightly and have a few people test that way?

Unfortunately, [this code comment](https://github.com/JuliaLang/libuv/pull/47/files#diff-54b530892931c350c937210c2284374eR2027) makes me doubt we can fully regression test this from Julia, but maybe the partial libuv test here is enough.

**Review by ihnorton — APPROVED** [review]

**Comment by ararslan** [comment]
Is this still relevant? @vtjnash

**Comment by ararslan** [comment]
Okay, I'll take that as a no. :P

**Pull request closed without merging**
