### PR TITLE
Fix execvpe not found error for glibc < 2.11

### PR DESCRIPTION
**Pull request by tkelman**
ref #24
This implementation is from musl-libc, which is MIT licensed. If this is deemed to be a "substantial portion," I can add in the copyright notice as well.

This should get skipped on a modern-enough distribution, would appreciate if someone could verify that.

### CODE REVIEW

**Comment by tkelman** [comment]
cc @simonster @Keno @vtjnash opinions?

**Comment by simonster** [comment]
As we've previously discussed, what is and isn't allowed after `vfork` is pretty nebulous and potentially implementation-dependent, but as long as the VLA on line 67 is guaranteed not to call `malloc` this looks safe to me.

**Comment by tkelman** [comment]
Thanks, that's a little over my head. It seems to be working okay on my RHEL5 box, and should be ifdef'ed out pretty much everywhere else.

**Comment by GlenHertz** [comment]
FYI. This patch fixes the Julia build on RHEL5.7 which is missing execvpe in libc.

**Comment by simonster** [comment]
@Keno Do you see any reason not to merge this?

**Comment by Keno** [comment]
No, this seems fine to me. Go ahead.

**Pull request merged**
