### PR TITLE
Building with NMake and Intel C++ Composer

### PR DESCRIPTION
**Pull request by vharavy**

### CODE REVIEW

**Comment by vtjnash** [comment]
I don't see any problems with this -- it is pretty much just adding self-contained files. Note, the `.gitignore` target `*.obj` can probably just go in the root directory.

Generally, I prefer patches like this to be submitted upstream and then cherry-picked locally. This allows the libuv developers to give their thoughts and review, and makes rebasing the `julia0.2` branch easier later. Since this really only adds files, it shouldn't have the rebasing difficulties, but it still should probably be submitted upstream to the Joyent folks. I'm ok with merging the pull request now, anyways.

**Comment by vharavy** [comment]
@vtjnash I didn't submit this patch to upstream repository because it is pretty much has nothing to do `libuv` (except for a correction in `atomicops-inl.h`). This patch should allow to build Julia on Windows with Intel C++ Compiler (and maybe Microsoft's compiler too) in future.

**Comment by vtjnash** [comment]
@VHaravy Yes, my tl;dr recommendation is to merge this here, but also submit upstream to see if the Joyent folks are interested too.

**Comment by StefanKarpinski** [comment]
I think the point is that the main libuv project might also be interested in being able to compile with other compilers. Ultimately it would be lovely if we could reach a state where we don't need to have our own libuv fork.

**Pull request merged**
