### PR TITLE
Use vfork() to launch processes on Linux

### PR DESCRIPTION
**Pull request by simonster**
Fixes JuliaLang/julia#3536 (some benchmarks there) and probably JuliaLang/julia#5385.

On Linux, `fork` can be very slow with processes with high memory use due to the overhead to copy page tables. This PR uses `clone` with the `CLONE_VM` option to create a new process that shares memory with the current process but uses a different stack. This is extremely fast by comparison to `fork`, but it requires some care with respect to global state.

`clone` must be passed a pointer to the new process's stack. I am currently passing a small portion of our current stack, since the child process does not need much stack space. It might be safer to use `posix_memalign` to allocate the new process's stack on the heap, since it is less likely that the parent's memory could be corrupted if `uv_spawn` returns before the child exits or calls `execvp`/`execvpe`, but that is not supposed to happen. There seems to be a measurable performance difference, but my benchmarks are not necessarily indicative of real-world use.

### CODE REVIEW

**Comment by vtjnash** [comment]
@loladiro / @JeffBezanson can you help review this? would also be nice to push this upstream

**Comment by simonster** [comment]
While I can't actually get this to break, discussion [here](http://www.sourceware.org/bugzilla/show_bug.cgi?id=10311) suggests it may not be the greatest idea. Apparently the JDK uses `vfork`, which is even scarier in that the parent and child share stacks, but might be safer? (The `vfork` man page has some pretty dire warnings about what happens if you try to make libc calls, but it seems that the [JDK](http://hg.openjdk.java.net/jdk8/jdk8/jdk/file/1a3de3cdc684/src/solaris/native/java/lang/UNIXProcess_md.c) [gets away](http://hg.openjdk.java.net/jdk8/jdk8/jdk/file/1a3de3cdc684/src/solaris/native/java/lang/childproc.c) with it.)

**Comment by JeffBezanson** [comment]
It is quite interesting that they decided to use `vfork` instead of `clone`. Makes me think we should do the same.

**Comment by simonster** [comment]
Here is the `vfork` version. Again, I am not sure I would call it "safe", since the man page states that behavior is undefined if the child process calls anything but `exec` or `_exit`, but we would not be the only ones using it to avoid the cost of `fork` on Linux.

One problem I see is that `execvp`/`execvpe` is not guaranteed not to allocate memory, although it looks like `glibc`'s implementation uses `alloca` unless the size is over 65536 bytes. We could check for this, or implement our own function for searching the path to run before `vfork`, but a path over 65536 bytes or an executable with over 65535 arguments is not exactly reasonable.

**Comment by vtjnash** [comment]
Note this was addressed a few months ago on the libuv issue lists (https://github.com/joyent/libuv/issues/978) with the resolution that vfork wouldn't be safe

**Comment by simonster** [comment]
That is indeed what the man page says, but both emacs and the JDK use it unsafely anyway.

As far as I can tell, the only approaches that do not rely on behavior that is undefined or known to be wrong are to use `clone` and make the syscalls directly in assembly (even the glibc `syscall` wrapper is unsafe) or to use a helper process (which could be launched safely with `vfork`/`execve` or `posix_spawn`) that sets the file descriptors and then `exec`s the actual command.

My impression is that `clone` with `CLONE_VM` would be safe if there were a way to give the new process its own thread-local storage, but while it is possible to set the thread local storage when using `clone`, there is no way to initialize it the way glibc wants. The situation is confusing enough that glibc's own tests rely on `clone` behavior that is technically undefined (see [this bug](https://www.sourceware.org/bugzilla/show_bug.cgi?id=11214) and the [resolution](https://sourceware.org/git/gitweb.cgi?p=glibc.git;a=blobdiff;f=nptl/Makefile;h=0fbfc4d3b47780f4c320d0f503a9f144b317040b;hp=82f2d0a4f48950860c89e8e76e7567dfc72621ba;hb=67ea2c9a69598edc6487c4b68942ab7b6bb27ad9;hpb=63cfe52b6d85b83ad5907484c048fc20f9b783fd) that stopped the test from failing but did not remove the undefined behavior).

If the safety of `vfork` is an issue, the helper process approach seems both tractable and portable, if a bit convoluted, and is probably still substantially faster than our current `fork` situation. It's crazy that the performance of `fork` for large processes on Linux is so bad and the available options are so poor.

**Comment by Keno** [comment]
FWIW, I disagree with their assessment that `vfork` is not safe. Our forking code looks quite a bit different than theirs and we have a different use case.

**Comment by simonster** [comment]
Bump. I've stayed on this libuv branch since it makes `Pkg.update()` far less painful, but since @loladiro updated libuv I need to either rebase this or discard it. Do we think that `vfork` is safe, or should I try the lightweight helper option I described in my previous comment and see how it performs?

**Comment by Keno** [comment]
I think we should go for it. The only concern I can see is the pipe that libuv uses to signal the exec error code. We need to make sure to avoid libc functions that may have state.

**Comment by simonster** [comment]
`vfork` suspends the calling thread until the child exits or calls `exec`, and the processes share memory until that point, so in this implementation I just save the error code in memory and the calling thread retrieves it when the child returns.

**Comment by Keno** [comment]
Ok, needs to be rebased onto the new branch then.

**Comment by JeffBezanson** [comment]
Yes, this is too nice to ignore.

**Pull request closed without merging**
