### PR TITLE
Fix segfaults on OSX

### PR DESCRIPTION
**Pull request by staticfloat**
This reverts commit 30d0897c79f48ee883589abea0bbc319240c44cb.

This has been [causing segfaults](https://github.com/JuliaLang/julia/issues/7344) on OSX builds.  Reverting this reversion fixes the issue.

### CODE REVIEW

**Comment by staticfloat** [comment]
@vtjnash @JeffBezanson notifying you guys that I've re-disabled the `isatty()` stuff.

**Comment by JeffBezanson** [comment]
This is really awful. Why do we have to be the only language that can't _read from standard in_? Surely there is a fix for this.

**Comment by vtjnash** [comment]
Julia can. It was cat - that couldn't. Maybe we should just revert back to blocking TTY for now

**Comment by JeffBezanson** [comment]
It's true that we can read from stdin in other cases, just not when a TTY and another program are involved. I suppose that situation is fairly rare.

**Comment by JeffBezanson** [comment]
Do we know why it segfaults on OS X but not linux? Does the same problem exist in both places with different symptoms, or is linux actually OK? If it works on linux, maybe we should enable this conditionally based on OS.

**Comment by Keno** [comment]
Libuv does magic on os x because kqueue doesn't work properly on /dev/tty. Unfortunately in this case there seems to be smoke coming out of it.

**Comment by JeffBezanson** [comment]
Ok let's make it conditional on linux, and accept the state of things on OS X, this being a fairly marginal use case.

**Comment by vtjnash** [comment]
I've disabled the whole mess until someone gets a chance to straighten it out (if that is even necessary). Everything should work, just with perhaps a minor delay after writing massive amounts of data to a tty.

**Comment by Keno** [comment]
Do you have any insight on what's causing the mess? Tracing the system calls reveals nothing unusual, yet somehow the stack of the select thread seems to be being corrupted.

**Comment by vtjnash** [comment]
not really. i also don't have time to chase this, since it doesn't need to be a 0.3 problem.

i was also concerned anyways this is using the wrong fd if the user runs `./julia > /dev/ttys002` (which I sometimes do when regression testing and want to split stdin/stdout/stderr)

**Comment by Keno** [comment]
I looked into this for the better part of today, but I give up. I have no idea why that message is even printed. The kernel calls look all correct and breakpoints there are never hit.

**Pull request merged**
