### PR TITLE
Use vfork() to launch processes on Linux

### PR DESCRIPTION
**Pull request by simonster**
This supersedes #19.

### CODE REVIEW

**Comment by simonster** [comment]
Is there a way to run the libuv tests? I get a bunch of undefined variable warnings when I try to build them using gyp, both with this branch and julia-uv0.11.20. Julia tests pass, though.

**Comment by simonster** [comment]
Bump

**Comment by Keno** [comment]
Bump. I think we should merge this. @JeffBezanson @vtjnash ?

**Comment by StefanKarpinski** [comment]
Do it.

**Comment by JeffBezanson** [comment]
+1

**Comment by vtjnash** [comment]
sure. needs to be rebased against the current branch however (julia-uv0.11.22). a quick glance shows this has a few bug fixes and API changes that are already incorporated upstream and need to be dropped from this

**Comment by vtjnash** [comment]
might even be worth bumping our julia version to v0.10.26 (stable) at this time

**Comment by simonster** [comment]
I'm happy to rebase this, but if we're going to bump libuv, it's easier if that happens first.

**Comment by simonster** [comment]
Are we going to bump libuv, or shall I rebase this?

**Comment by JeffBezanson** [comment]
@loladiro @vtjnash bump

**Comment by Keno** [comment]
I'll go ahead and bump libuv.

**Comment by Keno** [comment]
Now rebased (our libuv fork that is). The new branch is julia-uv0.11.26

**Pull request closed without merging**
