### PR TITLE
build: convert predefined $PLATFORM to lower case

### PR DESCRIPTION
**Pull request by staticfloat**
Here is the cherry-pick from https://github.com/joyent/libuv/commit/96a2df8

### CODE REVIEW

**Comment by vtjnash** [comment]
LGTM

**Comment by staticfloat** [comment]
I just tried installing Julia on a new computer and ran into the bug that inspired this patch. I thought to myself "I thought I fixed this"...... then realized it had never been merged.  Fixing that now!  :P

**Comment by staticfloat** [comment]
Do I need to do something specific to get this to show up on a clone of julia.git?

**Comment by pao** [comment]
You need to update the hash that the submodule points at.

**Pull request merged**
