### PR TITLE
Use vfork() to launch processes on Linux

### PR DESCRIPTION
**Pull request by simonster**
Rebased against julia-uv0.11.26. Supersedes #19 and #21.

### CODE REVIEW

**Comment by tkelman** [comment]
This causes a build failure on Red Hat.

```
    LINK src/flisp/flisp
/home/tkelman/Julia/julia/usr/lib/libuv.a(libuv_la-process.o): In function `uv__process_child_init':
/home/tkelman/Julia/julia/deps/libuv/src/unix/process.c:306: undefined reference to `execvpe'
collect2: ld returned 1 exit status
make[3]: *** [flisp] Error 1
make[2]: *** [flisp/libflisp.a] Error 2
```

`execvpe` is evidently not available in old versions of glibc. This may need to be gated under a feature-flag define or use an alternate implementation if older systems are going to still be supported.

**Comment by tkelman** [comment]
We could put in musl's version, it's pretty short and MIT licensed: http://git.musl-libc.org/cgit/musl/tree/src/process/execvp.c

Putting their definition (without the leading underscores) into `deps/libuv/src/unix/process.c` seems to be working for me. Make it conditional on `__GLIBC__`.`__GLIBC_MINOR__` being less than 2.11, according to http://linux.die.net/man/3/execvpe that's the first version that had `execvpe`.

**Comment by simonster** [comment]
We might also be able to set `environ` and call `execvp` as we do on other platforms instead of calling `execvpe`, although I'm not sure how this interacts with the shared memory situation.

**Comment by tkelman** [comment]
Can you show me what that would look like? I'd like to fix this quickly, having the release not work on Red Hat would be unfortunate.

**Comment by Keno** [comment]
Setting environ probably won't work.

**Comment by vtjnash** [comment]
Why not?

I suspect we want to set a define flag for whether to use vfork, so it can be more selectively enabled/disabled in its entirety

**Comment by Keno** [comment]
Because it would change the environ of the parent process.

**Comment by vtjnash** [comment]
Obviously true. But we also have the opportunity to change it back before uv_spawn returns (after the child succeeds at exec)

**Comment by Keno** [comment]
Will that work on mac? I thought environ was basically a function there.

**Comment by tkelman** [comment]
Aren't these changes linux only anyway?

**Comment by vtjnash** [comment]
Mac (and BSDs in general) don't have vfork AFAIK. They just have a much fast fork so it didn't matter

**Comment by Keno** [comment]
Nevermind then ;)

**Comment by Keno** [comment]
Mac does have vfork: https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man2/vfork.2.html

**Comment by tkelman** [comment]
Should we consider trying to upstream these changes, or would that be contingent on reconciling the bigger pipe API changes first?

**Comment by tkelman** [comment]
cc @simonster can you look at submitting this upstream? We're a bit overdue on rebasing against newer libuv, and we'll likely want to figure out how to use upstream more directly in the future. I think this might be the second-biggest change we have locally, aside from the pipe API differences.

**Pull request merged**
