### PR TITLE
Primarily, modify the libuv API to accomodate flags to uv_tcp_init()

### PR DESCRIPTION
**Pull request by nlhepler**
... but also "fix" a typo in the pipe API, or perhaps alter it to suit convention: libuv uses WRITABLE not WRITEABLE, also the former better passes the "google test".

### CODE REVIEW

**Comment by vtjnash** [comment]
Can you clarify what problem you are solving? TCP pipes are, by nature, bidirectional. It isn't particularly relevant to describe them as "read-only" or "write-only". (unlike pipes which are typically single directional).

The change `s/WRITEABLE/WRITABLE/` is certainly correct to make. It just leads to spurious compilation issues while everyone gets the change. It's probably good to make the fix though.

**Comment by Keno** [comment]
I agree with both @vtjnash and @StefanKarpinski. The pipe API is an exception since we absolutely needed to modify that to make `spawn` work the way we wanted, but I don't see the benefit in doing this to TcpSockets.

**Comment by nlhepler** [comment]
While I understand the bidirectional nature of sockets, I was thinking, perhaps, it might be useful to treat tty/pipes/sockets as generic data-source/-sink objects. For example, I have a cluster fabric that opens stdio as a tcp socket, and it doesn't make much sense to be writing to stdin -- catching this at runtime could be useful.

However I definitely understand not wanting to diverge from upstream too significantly, and this change is serving a (vanishingly) narrow use-case.

**Comment by Keno** [comment]
Surprisingly writing to STDIN is actually not that uncommon a use case, particularly when STDIN is a TTY. In any case, I if we want to implement that, it would probably make more sense to implement that in the Julia Structs rather than at the C level.

**Comment by Keno** [comment]
I'll merge the typo fix though (Thanks!).

**Comment by vtjnash** [comment]
@StefanKarpinski the spelling errors exist because of Keno's changes to libuv and do not exist upstream.

**Comment by StefanKarpinski** [comment]
Ok, that's fine then. Carry on.

**Pull request merged**
