### PR TITLE
cpuset: add FreeBSD support

### PR DESCRIPTION
**Pull request by vtjnash**
competitor to #42 😛

### CODE REVIEW

**Comment by ararslan** [comment]
Looks like we have a veritable Olympics on our hands! Yours is the simpler, more elegant solution, plus I trust that you know what you're doing more than I do, so I'll let you take home the gold. 😉

**Comment by ararslan** [comment]
Any chance of a patch release once this is fixed?

**Comment by vtjnash** [comment]
But yours arrived much faster, while mine is still attempting to build deps :). I don't actually know that much about FreeBSD, but just went with what seemed to work. I'm surprised our code diverged this much, since I thought I only saw the `pthread_getaffinity_np` in one header. I also put this in the public header since I am anticipating julia trying to use the header and needing UV_CPU_SETSIZE. But I still have many deps to build before I can test, and miles to go before I sleep.

Either way, your help will be appreciated in converging on a solution through review of both.

**Comment by vtjnash** [comment]
alright, I'm taking 👍 as lgtm

**Comment by ararslan** [comment]
Indeed. Thumbs are the universal language.

**Pull request merged**
